In [14]:
import numpy as np
X = np.array([[51, 55], [14, 19], [0, 4]])
print(X)

# 
X = np.array([[[1, 1 ], [2, 2 ] ], [[3, 3 ], [4, 4 ] ] ])
print(X)

X = X * np.array([10, 20 ])
print(X)
# 广播：看来还是会锁定最小的变量进行广播
# 广播有最小变量限制：X = np.array([[[1, 1, 1 ], [2, 2, 2 ] ], [[3, 3, 3 ], [4, 4, 4 ] ] ]) 不可

for row in X:
    print("row: ", end = "")
    print(row)

[[51 55]
 [14 19]
 [ 0  4]]
[[[1 1]
  [2 2]]

 [[3 3]
  [4 4]]]
[[[10 20]
  [20 40]]

 [[30 60]
  [40 80]]]
row: [[10 20]
 [20 40]]
row: [[30 60]
 [40 80]]
